modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC BY-NC-ND 4.0"
displayURL = "https://github.com/Faboslav/friends-and-foes-flowery-mooblooms"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes-flowery-mooblooms/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-flowery-mooblooms-forge"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minMinecraftVersion},)"

[[dependencies.${ modId }]]
modId = "friendsandfoes"
mandatory = true
versionRange = "[${friendsAndFoesVersion},)"
