name: "Publish"

on:
    release:
        types: [ published ]

env:
    VERSION_TYPE: release
    JAVA_VERSIONS: |
        Java 17
        Java 18
    GAME_VERSIONS: |
        1.19.3
    FABRIC_DEPENDENCIES: |
        fabric-api | depends | *
        friends-and-foes | depends | *
    FORGE_DEPENDENCIES: |
        friends-and-foes-forge | depends | *
    RETRY_ATTEMPTS: 3
    RELAY_DELAY: 10000
    VERSION_RESOLVER: latest

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 15

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4.1.1
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: 17
                    distribution: temurin

            - name: "Setup Gradle"
              uses: gradle/gradle-build-action@v2.11.1
              with:
                  cache-read-only: false

            - name: "Run Gradle build"
              run: ./gradlew build --no-daemon

            -   name: "Capture build artifacts"
                uses: actions/upload-artifact@v4.1.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"
                    path: |
                        fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                        forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                        LICENSE.txt

    publish-license:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish license to GitHub"
        timeout-minutes: 10

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v4.1.1
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish license to GitHub"
                uses: AButler/upload-release-assets@v3.0
                with:
                    files: 'LICENSE.txt'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to Github, CurseForge and Modrinth"
        timeout-minutes: 10

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v4.1.1
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Fabric to Github, CurseForge and Modrinth"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}

                    curseforge-id: 779833
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    modrinth-id: ECOSu6pa
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: fabric
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Fabric/Quilt)
                    version: fabric-${{ github.ref_name }}
                    dependencies: ${{ env.FABRIC_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-forge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to Github, CurseForge and Modrinth"
        timeout-minutes: 10

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v4.1.1
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Forge to Github, CurseForge and Modrinth"
                uses: Kir-Antipov/mc-publish@v3.2
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}

                    curseforge-id: 782443
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    modrinth-id: wYtDgIUZ
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: forge
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Forge)
                    dependencies: ${{ env.FORGE_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}