name: "Publish"

on:
    release:
        types: [ published ]

env:
    VERSION_TYPE: release
    JAVA_VERSIONS: |
        Java 17
        Java 18
    GAME_VERSIONS: |
        1.20
    FABRIC_DEPENDENCIES: |
        fabric-api | depends | *
        friends-and-foes | depends | *
    FORGE_DEPENDENCIES: |
        friends-and-foes-forge | depends | *
    QUILT_DEPENDENCIES: |
        qsl | depends | *
        friends-and-foes-quilt | depends | *
    RETRY_ATTEMPTS: 3
    RELAY_DELAY: 10000
    VERSION_RESOLVER: latest

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.6.0
                with:
                    java-version: 17
                    distribution: temurin
                    cache: gradle

            -   name: "Make gradle wrapper executable"
                run: chmod +x ./gradlew

            -   name: "Build with gradle"
                run: ./gradlew clean build --no-daemon --refresh-dependencies --stacktrace

            -   name: "Capture build artifacts"
                uses: actions/upload-artifact@v3.1.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"
                    path: |
                        fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                        forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                        quilt/build/libs/friendsandfoes-flowerymooblooms-quilt-${{ github.ref_name }}.jar
                        LICENSE.txt

    publish-license-to-release:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish license to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish license to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: 'LICENSE.txt'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Fabric to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Fabric to CurseForge"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    curseforge-id: 779833
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: fabric
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Fabric)
                    dependencies: ${{ env.FABRIC_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-fabric-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Fabric to Modrinth"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    modrinth-id: ECOSu6pa
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: fabric/build/libs/friendsandfoes-flowerymooblooms-fabric-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: fabric
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Fabric)
                    version: fabric-${{ github.ref_name }}
                    dependencies: ${{ env.FABRIC_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-forge-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Forge to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-forge-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Forge to CurseForge"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    curseforge-id: 782443
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: forge
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Forge)
                    dependencies: ${{ env.FORGE_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-forge-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Forge to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Forge to Modrinth"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    modrinth-id: wYtDgIUZ
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: forge/build/libs/friendsandfoes-flowerymooblooms-forge-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: forge
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Forge)
                    version: forge-${{ github.ref_name }}
                    dependencies: ${{ env.FORGE_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}


    publish-quilt-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Quilt to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Quilt to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: quilt/build/libs/friendsandfoes-flowerymooblooms-quilt-${{ github.ref_name }}.jar
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-quilt-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Quilt to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Quilt to CurseForge"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    curseforge-id: 782457
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: quilt/build/libs/friendsandfoes-flowerymooblooms-quilt-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: quilt
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Quilt)
                    dependencies: ${{ env.QUILT_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}

                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}

    publish-quilt-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Quilt to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "friends-and-foes-flowery-mooblooms"

            -   name: "Publish Quilt to Modrinth"
                uses: Kir-Antipov/mc-publish@v3.0
                with:
                    modrinth-id: DUug45uW
                    modrinth-featured: true
                    modrinth-unfeature-mode: version-intersection
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: quilt/build/libs/friendsandfoes-flowerymooblooms-quilt-${{ github.ref_name }}.jar
                    version-type: ${{ env.VERSION_TYPE }}
                    loaders: quilt
                    game-versions: ${{ env.GAME_VERSIONS }}
                    name: Friends&Foes - Flowery Mooblooms ${{ github.ref_name }} (Quilt)
                    version: quilt-${{ github.ref_name }}
                    dependencies: ${{ env.QUILT_DEPENDENCIES }}
                    java: ${{ env.JAVA_VERSIONS }}
                    retry-attempts: ${{ env.RETRY_ATTEMPTS }}
                    retry-delay: ${{ env.RETRY_DELAY }}
                    version-resolver: ${{ env.VERSION_RESOLVER }}